In [1]:
import numpy as np

In [3]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
y=np.array([[10,20,30],[40,50,60],[70,80,90]])

In [8]:
print(y)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


## adding two matrices

In [10]:
print(np.add(x,y))

[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [13]:
##multiplying two matrices


print(np.dot(x,y))

[[ 300  360  420]
 [ 660  810  960]
 [1020 1260 1500]]


## Transpose of a matrix

In [15]:
print(np.transpose(x))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [16]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## creating zeros and ones

In [24]:
z=np.zeros((3,3),dtype=complex)

In [25]:
print(z)

[[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]


In [26]:
type(z[0,0])

numpy.complex128

In [29]:
a=np.ones((2,2),dtype=int)

In [30]:
print(a)

[[1 1]
 [1 1]]


In [31]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Iterating through the array elements
## nested for loops
## nditer()

In [34]:
##nested for loop

for i in x:   ##[1,2,3]
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9


In [35]:
for i in np.nditer(x):
    print(i)

1
2
3
4
5
6
7
8
9


## Concatenating two matrices

In [40]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
y

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [49]:
arr1=np.concatenate((x,y))

In [46]:
arr2=np.concatenate((x,y),axis=1)

In [48]:
arr1.shape

(6, 3)

In [50]:
arr2.shape

(3, 6)

## arange -> a range

In [52]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [53]:
np.arange(1,6,2)

array([1, 3, 5])

In [54]:
np.arange(1,6,2,dtype=complex)

array([1.+0.j, 3.+0.j, 5.+0.j])